# Generated by Django 6.1 on 2026-09-01 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='published_data',
            new_name='published_date',
        ),
    ]
